// include/version.h
// (Autogenerated from cmake/version.h.in)
#pragma once

#define PROJECT_NAME "mylib"
#define PROJECT_VERSION_MAJOR "0"
#define PROJECT_VERSION_MINOR "1"
#define PROJECT_VERSION_PATCH "0"
#define PROJECT_VERSION "0.1.0"
